# Matrix Operations using numpy Python Library

## 1. Define Matrix in numpy

In [90]:
import numpy as np

A = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])

print(f'\nThe Matrix A is - \n{A}')

B = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])

print(f'\nThe Matrix B is - \n{B}')

# Get the data type of the data stored in the array. 
print("\n", A.dtype)

# Flatten the 2D array
print("\nFlattened Array - \n", A.flatten())

# Converting 2D array to 3D array
C = np.array([
  [1, 2, 3, 4, 5, 6],
  [7, 8, 9, 10, 11, 12]
])

print("\n2D Array - \n", C)
flat_array = C.flatten()

print("\n3D Array - ")
print(flat_array.reshape(3,2,2))

print("\nConverting List into Matrix - ")

m1 = np.matrix('1 2; 3 4; 5 6')
print("\nMatrix m1 :- \n", m1)

m2 = np.matrix('1 2 3; 4 5 6')
print("\nMatrix m2 :- \n", m2)

m3 = np.matrix('1 2 3; 4 5 6; 7 8 9')
print("\nMatrix m3 :- \n", m3)

print("\nDiagonal Matrix m1 :- \n", np.diagonal(m1))
print("\nDiagonal Matrix m2 :- \n", np.diagonal(m2))
print("\nDiagonal Matrix m3 :- \n", np.diagonal(m3))

# Minimum element in m3
print("\n Minimum element in m3 :- ", np.min(m3))

# Maximum element in m3
print("\n Maximum element in m3 :- ", np.max(m3))

# Multiplication of two Matrices
print("\n Multiplication of two Matrices m1 * m2 :- \n", m1 * m2)

# Transpose of the multiplication matrix m1 * m2 
print("\n Transpose of the multiplication matrix m1 * m2 :- \n", (m1 * m2).T)



The Matrix A is - 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The Matrix B is - 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 int32

Flattened Array - 
 [1 2 3 4 5 6 7 8 9]

2D Array - 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

3D Array - 
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

Converting List into Matrix - 

Matrix m1 :- 
 [[1 2]
 [3 4]
 [5 6]]

Matrix m2 :- 
 [[1 2 3]
 [4 5 6]]

Matrix m3 :- 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal Matrix m1 :- 
 [1 4]

Diagonal Matrix m2 :- 
 [1 5]

Diagonal Matrix m3 :- 
 [1 5 9]

 Minimum element in m3 :-  1

 Maximum element in m3 :-  9

 Multiplication of two Matrices m1 * m2 :- 
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]

 Transpose of the multiplication matrix m1 * m2 :- 
 [[ 9 19 29]
 [12 26 40]
 [15 33 51]]


### 1.1 Creating a Matrix with Specified Data Type

In [63]:
import numpy as np

# Creating an array of integers with a specified dtype
int_array = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]], dtype=np.uint8)
print("Integer Array:", int_array)
print("Data Type:", int_array.dtype)
print("Determinant : ", np.linalg.det(int_array))

# Creating an array of floating-point numbers
float_array = np.array([1.2, 2.3, 3.4], dtype=np.float64)
print("\nFloat Array:", float_array)
print("Data Type:", float_array.dtype)

# Creating an array of complex numbers
complex_array = np.array([1+2j, 3+4j], dtype=np.complex128)
print("\nComplex Array:", complex_array)
print("Data Type:", complex_array.dtype)

Integer Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Data Type: uint8
Determinant :  -9.51619735392994e-16

Float Array: [1.2 2.3 3.4]
Data Type: float64

Complex Array: [1.+2.j 3.+4.j]
Data Type: complex128


### 1.2 Creating a matrix of Zeros or Ones

In [64]:
# Creating a 3x3 matrix of zeros with dtype uint16
zeros_unsigned_matrix = np.zeros((3, 3), dtype=np.uint16)
print("\nZeros Unsigned Matrix:\n", zeros_unsigned_matrix)
print("Data Type:", zeros_unsigned_matrix.dtype)

# Creating a 2x2 matrix of ones with dtype uint32
ones_unsigned_matrix = np.ones((2, 2), dtype=np.uint32)
print("\nOnes Unsigned Matrix:\n", ones_unsigned_matrix)
print("Data Type:", ones_unsigned_matrix.dtype)


Zeros Unsigned Matrix:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Data Type: uint16

Ones Unsigned Matrix:
 [[1 1]
 [1 1]]
Data Type: uint32


### 1.3 Creating Identity Matrix

In [65]:
import numpy as np

# Creating a 2x2 identity matrix
identity_matrix_2x2 = np.identity(2)
print("2x2 Identity Matrix:\n", identity_matrix_2x2)

# Creating a 3x3 identity matrix with default float data type
identity_matrix_3x3_float = np.identity(3)
print("\n3x3 Identity Matrix (float):\n", identity_matrix_3x3_float)

# Creating a 3x3 identity matrix with integer data type
identity_matrix_3x3_int = np.identity(3, dtype=int)
print("\n3x3 Identity Matrix (int):\n", identity_matrix_3x3_int)

# Creating a 4x4 identity matrix
identity_matrix_4x4 = np.identity(4)
print("\n4x4 Identity Matrix:\n", identity_matrix_4x4)

2x2 Identity Matrix:
 [[1. 0.]
 [0. 1.]]

3x3 Identity Matrix (float):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3x3 Identity Matrix (int):
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 1.4 numpy.eye(n) Function To Create Identity Matrix
```
The numpy.eye() function is used to create an identity matrix, which is a square matrix with ones on the main diagonal and zeros elsewhere. 
The syntax for the function is as follows:

python
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

    Parameters:
        N       :   The number of rows in the output array.
        M       :   (Optional) The number of columns in the output array. If not specified, it defaults to N, creating a square matrix.
        k       :   (Optional) The diagonal to be filled with ones. The default is 0 (the main diagonal). 
                    A positive value refers to an upper diagonal, while a negative value refers to a lower diagonal.
        dtype   :   (Optional) The desired data type of the returned array (e.g., int, float).
        order   :   (Optional) Specifies whether the array should be stored in row-major ('C') or column-major ('F') order.
```

In [4]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

# Create a 2x3 matrix with ones on the main diagonal
non_square_matrix = np.eye(2, 3)
print("\n2x3 Matrix with Ones on the Diagonal:\n", non_square_matrix)

# Create a matrix with ones on the first upper diagonal
upper_diagonal_matrix = np.eye(4, k=1)
print("\nMatrix with Ones on the First Upper Diagonal:\n", upper_diagonal_matrix)

# Create a matrix with ones on the first lower diagonal
lower_diagonal_matrix = np.eye(4, k=-1)
print("\nMatrix with Ones on the First Lower Diagonal:\n", lower_diagonal_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

2x3 Matrix with Ones on the Diagonal:
 [[1. 0. 0.]
 [0. 1. 0.]]

Matrix with Ones on the First Upper Diagonal:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Matrix with Ones on the First Lower Diagonal:
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### 1.5 numpy.eye(n) Function To Create Identity Matrix
```
numpy.zeros(n, m)
The numpy.zeros() function creates an array filled with zeros of a specified shape and data type.

python
  numpy.zeros(shape, dtype=None, order='C')

    Parameters:
        shape   :   A tuple defining the dimensions of the array (e.g., (n, m) for an n x m matrix).
        dtype   :   (Optional) The desired data type of the returned array (e.g., int, float).
        order   :   (Optional) Specifies whether to store the array in row-major ('C') or column-major ('F') order.
```

In [9]:
# Create a 3x4 matrix filled with zeros
zero_matrix = np.zeros((3, 4))
print("3x4 Zero Matrix:\n", zero_matrix)

# Create a square zero matrix of size 2x2
square_zero_matrix = np.zeros((2, 2))
print("\n2x2 Zero Matrix:\n", square_zero_matrix)

# Create a square zero matrix of size 2x2 of type uint8
square_zero_matrix_uint8 = np.zeros((2, 2), dtype='uint8')
print("\n2x2 Zero Matrix uint8:\n", square_zero_matrix_uint8)

# Create a square zero matrix of size 2x2 of type uint16
square_zero_matrix_uint16 = np.zeros((2, 2), dtype='uint16')
print("\n2x2 Zero Matrix uint16:\n", square_zero_matrix_uint16)

3x4 Zero Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2x2 Zero Matrix:
 [[0. 0.]
 [0. 0.]]

2x2 Zero Matrix uint8:
 [[0 0]
 [0 0]]

2x2 Zero Matrix uint16:
 [[0 0]
 [0 0]]


### 1.6 Accessing Rows and Columns of the Matrix

In [ ]:
import numpy as np

# Create a 2D NumPy array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatrix:\n", array)

# Access the second row (index 1)
second_row = array[1, :]
print("\nSecond Row:", second_row)

# Access the first and third rows (indices 0 and 2)
selected_rows = array[[0, 2], :]
print("\nSelected Rows 1st and 3rd:\n", selected_rows)
'''
# Access the first two rows (indices 0 to 1)
range_rows = array[0:2, :]
print("\nRange of Rows 0th till 2nd row:\n", range_rows)

# Access the second column (index 1)
second_column = array[:, 1]
print("\nSecond Column:", second_column)

# Access the first and third columns (indices 0 and 2)
selected_columns = array[:, [0, 2]]
print("\nSelected Columns 0th and 2nd:\n", selected_columns)

# Access the first two columns (indices 0 to 1)
range_columns = array[:, 0:2]
print("\nRange of Columns 0th till 2nd column:\n", range_columns)
'''


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Second Row: [4 5 6]

Selected Rows 1st and 3rd:
 [[1 2 3]
 [7 8 9]]

Range of Rows 0th till 2nd row:
 [[1 2 3]
 [4 5 6]]

Second Column: [2 5 8]

Selected Columns 0th and 2nd:
 [[1 3]
 [4 6]
 [7 9]]

Range of Columns 0th till 2nd column:
 [[1 2]
 [4 5]
 [7 8]]


### 1.7 Deleting and Inserting Rows and Columns in the Matrix

- To insert a row into a matrix, you can use the numpy.insert() function. The syntax is as follows:

  ```
  numpy.insert(arr, obj, values, axis=0)

    Parameters:
        arr     : Input array.
        obj     : Index before which to insert the values.
        values  : Values to insert.
        axis    : Set to 0 to insert rows.
  ```

- To delete rows from a matrix, use the numpy.delete() function. The syntax is:

  ```
  numpy.delete(arr, obj, axis=0)

    Parameters:
        arr  : Input array.
        obj  : Index of the row(s) to delete.
        axis : Set to 0 for rows.
  ```

In [82]:
import numpy as np

# Define the initial matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal Matrix:\n", matrix)

# Define the new row to insert
new_row = np.array([7, 8, 9])

# Insert the new row at index 1
updated_matrix = np.insert(matrix, 1, new_row, axis=0)

print("\nMatrix after inserting a new row:\n", updated_matrix)

# Define the new column to insert
new_column = np.array([10, 12])

# Insert the new column at index 1
updated_matrix_with_column = np.insert(matrix, 1, new_column, axis=1)

print("\nMatrix after inserting a new column:\n", updated_matrix_with_column)

# Delete the second row (index 1)
matrix_after_deletion = np.delete(matrix, 1, axis=0)

print("\nMatrix after deleting the second row:\n", matrix_after_deletion)

# Delete the second column (index 1)
matrix_after_column_deletion = np.delete(matrix, 1, axis=1)

print("\nMatrix after deleting the second column:\n", matrix_after_column_deletion)



Original Matrix:
 [[1 2 3]
 [4 5 6]]

Matrix after inserting a new row:
 [[1 2 3]
 [7 8 9]
 [4 5 6]]

Matrix after inserting a new column:
 [[ 1 10  2  3]
 [ 4 12  5  6]]

Matrix after deleting the second row:
 [[1 2 3]]

Matrix after deleting the second column:
 [[1 3]
 [4 6]]


### 1.8 Traversing the Matrix row-wise with the help of for loops ➰ 

In row-wise traversal, you iterate through each row of the matrix, and for each row, you iterate through all its columns. Here’s how to do it: 

In [ ]:
import numpy as np

# Define a sample matrix
matrix = np.array([ [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]
                  ])

# Row-wise traversal
print("Row-wise Traversal:")
for i in range(matrix.shape[0]):      # Iterate over rows
    for j in range(matrix.shape[1]):  # Iterate over columns
        print(matrix[i, j], end=' ')  # Print element at (i, j)
    print()                           # New line after each row


Row-wise Traversal:
1 2 3 
4 5 6 
7 8 9 


### 1.9 Traversing the Matrix column-wise with the help of for loops ➰ 

In column-wise traversal, you iterate through each column of the matrix, and for each column, you iterate through all its rows. Here’s how to do it: 

In [11]:
# Column-wise traversal
print("Column-wise Traversal:")
for j in range(matrix.shape[1]):      # Iterate over columns
    for i in range(matrix.shape[0]):  # Iterate over rows
        print(matrix[i, j], end=' ')  # Print element at (i, j)
    print()                           # New line after each column

Column-wise Traversal:
1 4 7 
2 5 8 
3 6 9 


## 2. Matrix Addition

In [24]:
# Addition of Two Matrices 
print(f'\nThe addition of the Matrix A and Matrix B is - \n{A + B}')


The addition of the Matrix A and Matrix B is - 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## 3. Matrix Subtraction

In [19]:
# Subtraction of Two Matrices 
print(f'\nThe subtraction of the Matrix A and Matrix B is - \n{A - B}')


The subtraction of the Matrix A and Matrix B is - 
[[0 0 0]
 [0 0 0]
 [0 0 0]]


## 4. Matrix Multiplication

In [20]:
# Different ways of Matrix Multiplication
print(f'\n Method 1 : The multiplication of the Matrix A and Matrix B : "A.dot(B)" is - \n{A.dot(B)}')
print(f'\n Method 2 : The multiplication of the Matrix A and Matrix B : "B.dot(A)" is - \n{B.dot(A)}')
print(f'\n Method 3 : The multiplication of the Matrix A and Matrix B : "np.matmul(A, B)" is - \n{np.matmul(A,B)}')
print(f'\n Method 4 : The multiplication of the Matrix A and Matrix B : "A @ B" is - \n{A@B}')


 Method 1 : The multiplication of the Matrix A and Matrix B : "A.dot(B)" is - 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

 Method 2 : The multiplication of the Matrix A and Matrix B : "B.dot(A)" is - 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

 Method 3 : The multiplication of the Matrix A and Matrix B : "np.matmul(A, B)" is - 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

 Method 4 : The multiplication of the Matrix A and Matrix B : "A @ B" is - 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## 5. Elementwise Matrix Multiplication 

In [21]:
# Elementwise multiplication of two matrices 
print(f'\n The elementwise multiplication of the Matrix A and Matrix B : "A*B" is - \n{A*B}')


 The elementwise multiplication of the Matrix A and Matrix B : "A*B" is - 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## 6. Inverse of the Matrix

In [22]:
# Inverse of the Matrix
print(f'\n Inverse of the Matrix A is - \n{ np.linalg.inv(A) }')


 Inverse of the Matrix A is - 
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


## 7. Determinant of a Matrix

The determinant of a matrix is a scalar value that provides important information about the matrix, particularly in terms of its invertibility and the volume scaling factor of linear transformations represented by the matrix. 

The determinant is defined only for square matrices (matrices with the same number of rows and columns).
Calculation of the Determinant

The method for calculating the determinant varies depending on the size of the matrix:
1. **For a 2x2 Matrix**
     $$A = 
     \begin{bmatrix}
     a & b  \\
     c & d
     \end{bmatrix}
     $$

     the determinant is calculated as:
     $$ det(A)=ad−bc $$

     This is obtained by cross-multiplying the elements and subtracting the products13.

2. **For a 3x3 Matrix**
     $$A = 
     \begin{bmatrix}
     a & b & c \\
     d & e & f \\
     g & h & i
     \end{bmatrix}
     $$

     The determinant can be calculated using the formula:

     $$det(A)=a(ei−fh)−b(di−fg)+c(dh−eg)$$

     This involves calculating the determinants of 2x2 matrices formed by omitting one row and one column for each element in the first row.

3. **For Larger Matrices (n x n)**  
     
     For larger matrices, determinants can be computed using various methods, including:
     
     **Cofactor Expansion**:  
      Choose any row or column, calculate the cofactor for each element, multiply by that element, and sum them up with alternating signs.
     
     **Row Reduction** :  
      Reduce the matrix to row echelon form using elementary row operations, then multiply the diagonal elements. The determinant will be affected by any row swaps or scaling operations performed during this process25.

     **Properties of Determinants**
     - The determinant is zero if and only if the matrix is singular (not invertible).
     - The determinant can provide insights into the linear independence of vectors represented by rows or columns of the matrix.
     - The absolute value of the determinant gives the volume scaling factor when transforming geometric shapes using linear transformations.

     In summary, determinants are crucial in linear algebra for understanding matrix properties and solving systems of equations. They can be calculated using straightforward formulas for small matrices or more complex methods for larger ones.

In [56]:
# Determinant of the Matrix
A = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])
print(f'\n Inverse of the Matrix A is - \n{ np.linalg.det(A) }')


 Inverse of the Matrix A is - 
-9.51619735392994e-16


## 8. Eigen Values and Eigen Vector of a Matrix

**Resources**
1. https://youtu.be/h8sg_XBp6VA
2. https://youtu.be/PFDu9oVAE-g
3. https://youtu.be/e50Bj7jn9IQ

In [18]:
import numpy as np

# Define a square matrix
A = np.array([[4, 2],
              [1, 3]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the results
print("\nPrinting Eigen Values and Eigen Vectors of the Matrix A : \n")
print("Eigenvalues:", eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


# Eigen Values of a Matrix
print("\n=========================================================== ")
print("Printing just Eigen Values of the Matrix C : \n")
C = np.array([
  [2, 5, 7],
  [1, 2, 3],
  [7, 8, 2]
])
print(np.linalg.eigvals(C))



Printing Eigen Values and Eigen Vectors of the Matrix A : 

Eigenvalues: [5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

Printing just Eigen Values of the Matrix C : 

[11.72403766 -5.52328145 -0.2007562 ]


#

## 9. Raising Matrix to Different Powers 

In [50]:
# Define a square matrix
matrix = np.array([[2, 5], [1, 3]])

# Calculate different powers
mat_power_2 = np.linalg.matrix_power(matrix, 2)  # Square of the matrix
mat_power_3 = np.linalg.matrix_power(matrix, 3)  # Cube of the matrix
mat_power_0 = np.linalg.matrix_power(matrix, 0)  # Identity matrix

print("Matrix:\n", matrix)
print("Matrix squared:\n", mat_power_2)
print("Matrix cubed:\n", mat_power_3)
print("Matrix to the power of 0 (Identity):\n", mat_power_0)

Matrix:
 [[2 5]
 [1 3]]
Matrix squared:
 [[ 9 25]
 [ 5 14]]
Matrix cubed:
 [[ 43 120]
 [ 24  67]]
Matrix to the power of 0 (Identity):
 [[1 0]
 [0 1]]


## 10. Calculating Inverse of a Matrix

In [51]:
# Calculate the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

print("Inverse of the matrix:\n", inverse_matrix)

Inverse of the matrix:
 [[ 3. -5.]
 [-1.  2.]]


# 11. Combining Powers and Inverse

In [54]:
# Calculate the inverse and raise it to a power
inverse_power = np.linalg.matrix_power(inverse_matrix, -2)

print("Inverse of a matrix is not equal to the matrix power -1")
print("Inverse raised to power -1:\n", np.linalg.matrix_power(inverse_matrix, -1))
print("Inverse raised to power -2:\n", inverse_power)

Inverse of a matrix is not equal to the matrix power -1
Inverse raised to power -1:
 [[2. 5.]
 [1. 3.]]
Inverse raised to power -2:
 [[ 9. 25.]
 [ 5. 14.]]


## 12. Row Echelon and Reduced Row Echelon Form Of a Matrix 

1. **Conditions for the Row Echelon Form of a Matrix**
  1. Leading element of each row must be unity (1)
  2. If any zero row is present, then it must be at last. 
  3. In each row, number of zeros must be greater than the number of zeros in previous row.
    
    Note: This form is used to find the Rank of a matrix
  
  $$ A = 
  \begin{bmatrix}
  0 & 1 & 2 & 7 \\
  0 & 0 & 1 & 9 \\         
  0 & 0 & 0 & 0
  \end{bmatrix}        ✅
  $$
  
  $$B = 
  \begin{bmatrix}
  1 & 6 & 8 & 9 \\
  0 & 0 & 1 & 7 \\
  0 & 0 & 0 & 1
  \end{bmatrix}        ✅
  $$
      
  $$C = 
  \begin{bmatrix}
  0 & 0 & 1 & 5  \\
  0 & 1 & -3 & 8 \\
  0 & 0 & 1 & 2
  \end{bmatrix}        ❌
  $$
      
  $$D = 
  \begin{bmatrix}
  0 & 1 & 6 \\
  0 & 0 & 0 \\
  0 & 0 & 1 
  \end{bmatrix}        ❌
  $$
  
    Row Echelon Form        := Matrix A and Matrix B  
    Not in Row Echelon Form := Matrix C and Matrix D

2. **Conditions for the Reduced Row Echelon Form of a Matrix**  
  The Matrix should be in Echelon Form and below and Above of the leading element (if present) must be zero.

  $$ A = 
  \begin{bmatrix}
  0 & 1 & 0 & -3 \\
  0 & 0 & 1 & 6 \\         
  0 & 0 & 0 & 0
  \end{bmatrix}        ✅
  $$
  
  $$B = 
  \begin{bmatrix}
  1 & 5 & 0 & 0 \\
  0 & 0 & 1 & 0 \\
  0 & 0 & 0 & 1
  \end{bmatrix}        ✅
  $$
      
  $$C = 
  \begin{bmatrix}
  0 & 1 & 0 & 3  \\
  0 & 0 & 1 & 6 \\
  0 & 0 & 5 & 0
  \end{bmatrix}        ❌
  $$
      
  $$D = 
  \begin{bmatrix}
  1 & 5 & 0 & 0 \\
  0 & 0 & 1 & 4 \\
  0 & 0 & 0 & 1
  \end{bmatrix}        ❌
  $$


In [ ]:
import numpy as np
from sympy import Matrix

# Define your matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Convert the NumPy array to a SymPy Matrix
sympy_matrix = Matrix(matrix)

print("\nOriginal matrix :- \n", sympy_matrix)

# Compute the RREF
rref_matrix, pivot_columns = sympy_matrix.rref()

print("\nReduced Row Echelon Form:")
print(rref_matrix)

print("\nPivot Columns:", pivot_columns)


Original matrix :- 
 Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Reduced Row Echelon Form:
Matrix([[1, 0, -1], [0, 1, 2], [0, 0, 0]])

Pivot Columns: (0, 1)


## 13. Rank Of a Matrix 

**Rank Definition:**   
The rank of a matrix is defined as the maximum number of linearly independent row or column vectors in the matrix.   
It provides insight into the dimensionality of the vector space spanned by its rows or columns.

**Method 1**  
Number of non zero rows of a matrix is known as the Rank of a Matrix.

  $$ A = 
  \begin{bmatrix}
  1 & 2 & 3 \\
  0 & 0 & 0 \\         
  1 & 8 & 0
  \end{bmatrix}        R(A) = 2 \ \  Or \ \  rank(A)=2 
  $$
  
  $$B = 
  \begin{bmatrix}
  1 & 6 & 8 & 9 \\
  0 & 0 & 1 & 7 \\
  0 & 0 & 0 & 1
  \end{bmatrix}        R(A) = 3 \ \  Or \ \  rank(A)=3
  $$
      
  $$ D = 
  \begin{bmatrix}
  9 & 1 & 6 \\
  3 & 2 & 0 \\
  0 & 0 & 1 
  \end{bmatrix}        R(A) = 2 \ \  Or \ \  rank(A)=2
  $$  

**Method 2**  
If the determinant of the matrix is != 0, then the rank of the matrix = number of rows  
If the determinant of the matrix is == 0, then the rank of the matrix < number of rows 

In [71]:
import numpy as np

# Define a matrix
matrixA = np.array([[1, 2, 3, 23],
                      [4, 5, 6, 25],
                      [7, 8, 9, 28],
                      [10, 11, 12, 41]])

# Calculate the rank of the matrix
rank = np.linalg.matrix_rank(matrixA)

print("The Rank of the Matrix:", rank)


The Rank of the Matrix: 3


## 14. Solving Systems Of Linear Equations with Python

**Resources** -  
1. https://www.youtube.com/watch?v=UbuBwHbZTU8
2. https://www.youtube.com/watch?v=jTCCgxUXhW4 
3. https://www.youtube.com/watch?v=5eBmb8ir-uA

```
Consider the system of Liner Equations.

x + y + z = 6
2y + 5z = -4
2x + 5y -z = 27

This can be represented as below :-  

|1, 1,  1| |x| = | 6|
|0, 2,  5| |y| = |-4|
|2, 5, -1| |z| = |27| 

A * X = B
X = B/A = B * (A^-1) 
```

#### 14.1 Solving System Of Linear Equations Using "NumPy" Library

In [86]:
import numpy as np

A = np.array([  [1, 1,  1],
                [0, 2,  5],
                [2, 5, -1]
            ])

B = np.array([
              [6], [-4], [27]
            ])

result = np.dot(np.linalg.inv(A), B)
print(result)

# Alternate method of solving 
print("\n")
print(np.linalg.solve(A, B))

[[ 5.]
 [ 3.]
 [-2.]]


[[ 5.]
 [ 3.]
 [-2.]]


#### 14.2 Solving System Of Linear Equations Using "SymPy" Library

In [2]:
from sympy.interactive import printing 
printing.init_printing(use_latex=True)
from sympy import Eq, solve_linear_system, Matrix 
from numpy import linalg
import numpy as np
import sympy as sp

print("============ Using sympy ============= ")

eq1 = sp.Function('eq1')
eq2 = sp.Function('eq2')
eq3 = sp.Function('eq3')

x, y, z = sp.symbols('x y z')
eq1 = Eq(x + y + z, 6)
eq2 = Eq(0*x + 2*y + 5*z, -4)
eq3 = Eq(2*x + 5*y - z, 27)

display(eq1)
display(eq2)
display(eq3)

system = Matrix(([1, 1, 1, 6], [0, 2, 5, -4], [2, 5, -1, 27]))
solve_linear_system(system, x, y, z)

============ Using sympy ============= 


### 14.3 LU Decomposition Method in Python 
**Resource** 
1. https://www.youtube.com/watch?v=5eBmb8ir-uA

## 15. Diagonalization 

```
Diagonalization in linear algebra refers to the process of converting a square matrix into a diagonal matrix, which is a matrix where all non-diagonal elements are zero.
A matrix A is said to be diagonalizable, if there exists an invertible matrix PP and a diagonal matrix D such that:
```
  $$ A = PDP^{−1} $$
```
Key Concepts
    Diagonal Matrix: A diagonal matrix DD has the form:
```

$$ D = 
\begin{bmatrix}
d1 & 0 & ... & 0 \\
0 & d2 & ... & 0 \\         
. & .  & ... & . \\         
. & .  & ... & . \\         
0 & 0  & 0   & dn
\end{bmatrix}           
$$

```   
where di are the eigenvalues of the matrix A.
    
Eigenvalues and Eigenvectors :-  
    The diagonalization process involves finding the eigenvalues and eigenvectors of the matrix. 
    A matrix is diagonalizable if it has enough linearly independent eigenvectors to form the matrix P.
    
Conditions for Diagonalizability :-  
    A square matrix A is diagonalizable if it has n linearly independent eigenvectors, where n is the size of the matrix.

Steps to Diagonalize a Matrix :-  
    Find Eigenvalues                : Compute the eigenvalues of the matrix using the characteristic polynomial.
    Find Eigenvectors               : For each eigenvalue, compute the corresponding eigenvector(s).
    Form Matrix P                   : Construct the matrix PP using the eigenvectors as columns.
    Construct Diagonal Matrix  D    : Form the diagonal matrix DD with the eigenvalues on its diagonal.
    Verify                          : Check that A = PDP^−1.
    
``` 



In [20]:
import numpy as np
from scipy.linalg import eig

# Define a square matrix
A = np.array([[4, 1],
              [2, 3]])

# Step 1: Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = eig(A)

# Step 2: Form the diagonal matrix D
D = np.diag(eigenvalues)

# Step 3: Form the invertible matrix P from eigenvectors
P = eigenvectors

# Step 4: Compute P inverse
P_inv = np.linalg.inv(P)

# Verify that A = P * D * P_inv
A_reconstructed = P @ D @ P_inv

print("Original Matrix A:\n", A)
print("\nEigen Values :\n", eigenvalues)
print("\nDiagonal Matrix (Diagonal Elements of D):\n", D)
print("\nMatrix P (Eigenvectors):\n", P)
print("\nReconstructed Matrix (PDP^-1):\n", A_reconstructed)


Original Matrix A:
 [[4 1]
 [2 3]]

Eigen Values :
 [5.+0.j 2.+0.j]

Diagonal Matrix (Diagonal Elements of D):
 [[5.+0.j 0.+0.j]
 [0.+0.j 2.+0.j]]

Matrix P (Eigenvectors):
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

Reconstructed Matrix (PDP^-1):
 [[4.+0.j 1.+0.j]
 [2.+0.j 3.+0.j]]
